/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface JuzMapping {
    juzNumber: bigint;
    startingAyah: bigint;
    startingSurah: bigint;
}
export interface Surah {
    ayahCount: bigint;
    nameArabic: string;
    revelationType: string;
    nameEnglish: string;
    number: bigint;
}
export interface Bookmark {
    surahNumber: bigint;
    ayahNumber: bigint;
}
export interface Ayah {
    surahNumber: bigint;
    uthmaniText: string;
    urduTranslation: string;
    englishTranslation: string;
    ayahNumber: bigint;
}
export interface backendInterface {
    addAyah(ayah: Ayah): Promise<void>;
    addJuzMapping(juz: JuzMapping): Promise<void>;
    addSurah(surah: Surah): Promise<void>;
    getAyahs(surahNumber: bigint): Promise<Array<Ayah>>;
    getBookmark(): Promise<Bookmark | null>;
    getJuzIndex(): Promise<Array<JuzMapping>>;
    getSurah(surahNumber: bigint): Promise<Surah>;
    getSurahs(): Promise<Array<Surah>>;
    resetData(): Promise<void>;
    saveBookmark(surahNumber: bigint, ayahNumber: bigint): Promise<void>;
}
import type { Bookmark as _Bookmark } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addAyah(arg0: Ayah): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addAyah(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addAyah(arg0);
            return result;
        }
    }
    async addJuzMapping(arg0: JuzMapping): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addJuzMapping(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addJuzMapping(arg0);
            return result;
        }
    }
    async addSurah(arg0: Surah): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addSurah(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addSurah(arg0);
            return result;
        }
    }
    async getAyahs(arg0: bigint): Promise<Array<Ayah>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAyahs(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAyahs(arg0);
            return result;
        }
    }
    async getBookmark(): Promise<Bookmark | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getBookmark();
                return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBookmark();
            return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getJuzIndex(): Promise<Array<JuzMapping>> {
        if (this.processError) {
            try {
                const result = await this.actor.getJuzIndex();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getJuzIndex();
            return result;
        }
    }
    async getSurah(arg0: bigint): Promise<Surah> {
        if (this.processError) {
            try {
                const result = await this.actor.getSurah(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSurah(arg0);
            return result;
        }
    }
    async getSurahs(): Promise<Array<Surah>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSurahs();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSurahs();
            return result;
        }
    }
    async resetData(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.resetData();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.resetData();
            return result;
        }
    }
    async saveBookmark(arg0: bigint, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveBookmark(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveBookmark(arg0, arg1);
            return result;
        }
    }
}
function from_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Bookmark]): Bookmark | null {
    return value.length === 0 ? null : value[0];
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
