/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Ayah = IDL.Record({
  'surahNumber' : IDL.Nat,
  'uthmaniText' : IDL.Text,
  'urduTranslation' : IDL.Text,
  'englishTranslation' : IDL.Text,
  'ayahNumber' : IDL.Nat,
});
export const JuzMapping = IDL.Record({
  'juzNumber' : IDL.Nat,
  'startingAyah' : IDL.Nat,
  'startingSurah' : IDL.Nat,
});
export const Surah = IDL.Record({
  'ayahCount' : IDL.Nat,
  'nameArabic' : IDL.Text,
  'revelationType' : IDL.Text,
  'nameEnglish' : IDL.Text,
  'number' : IDL.Nat,
});
export const Bookmark = IDL.Record({
  'surahNumber' : IDL.Nat,
  'ayahNumber' : IDL.Nat,
});

export const idlService = IDL.Service({
  'addAyah' : IDL.Func([Ayah], [], []),
  'addJuzMapping' : IDL.Func([JuzMapping], [], []),
  'addSurah' : IDL.Func([Surah], [], []),
  'getAyahs' : IDL.Func([IDL.Nat], [IDL.Vec(Ayah)], ['query']),
  'getBookmark' : IDL.Func([], [IDL.Opt(Bookmark)], ['query']),
  'getJuzIndex' : IDL.Func([], [IDL.Vec(JuzMapping)], ['query']),
  'getSurah' : IDL.Func([IDL.Nat], [Surah], ['query']),
  'getSurahs' : IDL.Func([], [IDL.Vec(Surah)], ['query']),
  'resetData' : IDL.Func([], [], []),
  'saveBookmark' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Ayah = IDL.Record({
    'surahNumber' : IDL.Nat,
    'uthmaniText' : IDL.Text,
    'urduTranslation' : IDL.Text,
    'englishTranslation' : IDL.Text,
    'ayahNumber' : IDL.Nat,
  });
  const JuzMapping = IDL.Record({
    'juzNumber' : IDL.Nat,
    'startingAyah' : IDL.Nat,
    'startingSurah' : IDL.Nat,
  });
  const Surah = IDL.Record({
    'ayahCount' : IDL.Nat,
    'nameArabic' : IDL.Text,
    'revelationType' : IDL.Text,
    'nameEnglish' : IDL.Text,
    'number' : IDL.Nat,
  });
  const Bookmark = IDL.Record({
    'surahNumber' : IDL.Nat,
    'ayahNumber' : IDL.Nat,
  });
  
  return IDL.Service({
    'addAyah' : IDL.Func([Ayah], [], []),
    'addJuzMapping' : IDL.Func([JuzMapping], [], []),
    'addSurah' : IDL.Func([Surah], [], []),
    'getAyahs' : IDL.Func([IDL.Nat], [IDL.Vec(Ayah)], ['query']),
    'getBookmark' : IDL.Func([], [IDL.Opt(Bookmark)], ['query']),
    'getJuzIndex' : IDL.Func([], [IDL.Vec(JuzMapping)], ['query']),
    'getSurah' : IDL.Func([IDL.Nat], [Surah], ['query']),
    'getSurahs' : IDL.Func([], [IDL.Vec(Surah)], ['query']),
    'resetData' : IDL.Func([], [], []),
    'saveBookmark' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };