/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Ayah {
  'surahNumber' : bigint,
  'uthmaniText' : string,
  'urduTranslation' : string,
  'englishTranslation' : string,
  'ayahNumber' : bigint,
}
export interface Bookmark { 'surahNumber' : bigint, 'ayahNumber' : bigint }
export interface JuzMapping {
  'juzNumber' : bigint,
  'startingAyah' : bigint,
  'startingSurah' : bigint,
}
export interface Surah {
  'ayahCount' : bigint,
  'nameArabic' : string,
  'revelationType' : string,
  'nameEnglish' : string,
  'number' : bigint,
}
export interface _SERVICE {
  'addAyah' : ActorMethod<[Ayah], undefined>,
  'addJuzMapping' : ActorMethod<[JuzMapping], undefined>,
  'addSurah' : ActorMethod<[Surah], undefined>,
  'getAyahs' : ActorMethod<[bigint], Array<Ayah>>,
  'getBookmark' : ActorMethod<[], [] | [Bookmark]>,
  'getJuzIndex' : ActorMethod<[], Array<JuzMapping>>,
  'getSurah' : ActorMethod<[bigint], Surah>,
  'getSurahs' : ActorMethod<[], Array<Surah>>,
  'resetData' : ActorMethod<[], undefined>,
  'saveBookmark' : ActorMethod<[bigint, bigint], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];